AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: CloudGuruChallenge Event-Driven Python
Globals:
  Function:
    Runtime: python3.8
    MemorySize: 128
    Timeout: 30
    Tags:
      Application: CGC Event-Driven Python
Parameters:
  URLDatasetNYT:
    Type: String
  URLDatasetJHU:
    Type: String
Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      RoleName:
        Fn::Sub: ${AWS::StackName}-LambdaExecutionRole
      Policies:
      - PolicyName:
          Fn::Sub: ${AWS::StackName}-LambdaExecutionRole
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: '*'
          - Effect: Allow
            Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:Query
            - dynamodb:DeleteItem
            Resource:
            - Fn::GetAtt:
              - DynamoDBTable
              - Arn
            - Fn::Sub: ${DynamoDBTable.Arn}/index/*
          - Effect: Allow
            Action:
            - xray:PutTraceSegments
            - xray:PutTelemetryRecords
            Resource: '*'
  DailyETLTrigger:
    Type: AWS::Events::Rule
    DependsOn:
    - DataIngestionFunction
    Properties:
      Name:
        Fn::Sub: ${AWS::StackName}-ETL-Trigger
      Description: Daily trigger for CGC ETL pipeline
      ScheduleExpression: rate(1 day)
      State: ENABLED
      Targets:
      - Arn:
          Fn::GetAtt:
          - DataIngestionFunction
          - Arn
        Id: ETL_Lambda_function
  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Ref: DataIngestionFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt:
        - DailyETLTrigger
        - Arn
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Fn::Sub: ${AWS::StackName}-Data
      AttributeDefinitions:
      - AttributeName: PK
        AttributeType: S
      - AttributeName: date
        AttributeType: S
      KeySchema:
      - AttributeName: PK
        KeyType: HASH
      - AttributeName: date
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  ProcessDynamoDBStream:
    DependsOn:
    - DynamoDBTable
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler
      Runtime: python3.8
      Policies: AWSLambdaDynamoDBExecutionRole
      FunctionName:
        Fn::Sub: ${AWS::StackName}-DatabaseStream
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream:
              Fn::GetAtt:
              - DynamoDBTable
              - StreamArn
            BatchSize: 1
            StartingPosition: TRIM_HORIZON
      CodeUri: s3://quinceleaf-sam-artifacts/CGC-COVID/044586c1c7072eca46764d53ef0b9c2f
  DataIngestionFunction:
    DependsOn:
    - DynamoDBTable
    Type: AWS::Serverless::Function
    Properties:
      Handler: cgc-covid-etl.lambda_handler
      Tracing: Active
      FunctionName:
        Fn::Sub: ${AWS::StackName}-ETL
      Description:
        Fn::Sub:
        - Function for ${ResourceName}
        - ResourceName: ETL of daily dataset
      CodeUri: s3://quinceleaf-sam-artifacts/CGC-COVID/419fe050b7f23dc37e52d3a3d995becb
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Environment:
        Variables:
          TABLE_NAME:
            Ref: DynamoDBTable
          URL_DATASET_NYT:
            Ref: URLDatasetNYT
          URL_DATASET_JHU:
            Ref: URLDatasetJHU
