AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: CloudGuruChallenge Event-Driven Python

Globals:
  Function:
    Runtime: python3.8
    MemorySize: 128
    Timeout: 30
    Tags:
      Application: CGC Event-Driven Python

Parameters:
  URLDatasetNYT:
    Type: String
  URLDatasetJHU:
    Type: String

Resources:
  # ––– IAM ROLES
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      RoleName: !Sub ${AWS::StackName}-LambdaExecutionRole
      Policies:
        - PolicyName: !Sub ${AWS::StackName}-LambdaExecutionRole
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:Query
                  - dynamodb:DeleteItem
                Resource:
                  - !GetAtt DynamoDBTable.Arn
                  - !Sub ${DynamoDBTable.Arn}/index/*
              - Effect: Allow
                Action:
                  - xray:PutTraceSegments
                  - xray:PutTelemetryRecords
                Resource: "*"

  # ––– EVENTBRIDGE TRIGGER
  DailyETLTrigger:
    Type: AWS::Events::Rule
    DependsOn:
      - DataIngestionFunction
    Properties:
      Name: !Sub ${AWS::StackName}-ETL-Trigger
      Description: Daily trigger for CGC ETL pipeline
      ScheduleExpression: rate(1 day)
      State: ENABLED
      Targets:
        - Arn: !GetAtt DataIngestionFunction.Arn
          Id: ETL_Lambda_function

  # ––– EVENTBRIDGE IAM ROLE
  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DataIngestionFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt DailyETLTrigger.Arn

  # ––– DATABASE
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-Data
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: date
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: date
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  # ––– FUNCTION: STREAM
  ProcessDynamoDBStream:
    DependsOn:
      - DynamoDBTable
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler
      Runtime: python3.8
      Policies: AWSLambdaDynamoDBExecutionRole
      FunctionName: !Sub ${AWS::StackName}-DatabaseStream
      Description: !Sub
        - Function for ${ResourceName}
        - ResourceName: Process stream of daily update
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt DynamoDBTable.StreamArn
            BatchSize: 1
            StartingPosition: TRIM_HORIZON

  # ––– FUNCTION: ETL
  DataIngestionFunction:
    DependsOn:
      - DynamoDBTable
    Type: AWS::Serverless::Function
    Properties:
      Handler: cgc-covid-etl.lambda_handler
      Tracing: Active
      FunctionName: !Sub ${AWS::StackName}-ETL
      Description: !Sub
        - Function for ${ResourceName}
        - ResourceName: ETL of daily dataset
      CodeUri: functions/etl/cgc-covid-etl.py
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref DynamoDBTable
          URL_DATASET_NYT: !Ref URLDatasetNYT
          URL_DATASET_JHU: !Ref URLDatasetJHU
