AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: CloudGuruChallenge Event-Driven Python

Globals:
  Function:
    Runtime: python3.8
    MemorySize: 128
    Timeout: 45
    Tags:
      Application: CGC Event-Driven Python

Parameters:
  URLDatasetNYT:
    Type: String
  URLDatasetJHU:
    Type: String
  DomainARN:
    Type: String

Resources:
  # ––– IAM ROLES
  ETLFunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      RoleName: !Sub ${AWS::StackName}-ETLFunctionExecutionRole
      Policies:
        - PolicyName: !Sub ${AWS::StackName}-ETLFunctionExecutionRole
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - SNS:Publish
                Resource:
                  - !Ref DatabaseUpdatedTopic
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:Query
                  - dynamodb:DeleteItem
                Resource:
                  - !GetAtt DynamoDBTable.Arn
                  - !Sub ${DynamoDBTable.Arn}/index/*
              - Effect: Allow
                Action:
                  - xray:PutTraceSegments
                  - xray:PutTelemetryRecords
                Resource: "*"

  StreamFunctionExecutionRole:
    Type: AWS::IAM::Role
    DependsOn:
      - DatabaseUpdatedTopic
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      RoleName: !Sub ${AWS::StackName}-StreamFunctionExecutionRole
      Policies:
        - PolicyName: !Sub ${AWS::StackName}-StreamFunctionExecutionRole
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - SNS:Publish
                Resource:
                  - !Ref DatabaseUpdatedTopic
              - Effect: Allow
                Action:
                  - dynamodb:DescribeStream
                  - dynamodb:GetRecords
                  - dynamodb:GetShardIterator
                  - dynamodb:ListStreams
                Resource:
                  - !GetAtt DynamoDBTable.Arn
                  - !Sub ${DynamoDBTable.Arn}/stream/*
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  # ––– API
  DashboardApi:
    Type: AWS::Serverless::Api
    DependsOn:
      - DashboardApiLog
      - DashboardApiFunction
    Properties:
      Name: !Sub ${AWS::StackName}-DashboardApi
      StageName: prod
      Cors:
        AllowMethods: "'GET,OPTIONS'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      Domain:
        DomainName: cgc-covid-dashboard.quinceleaf.app
        CertificateArn: !Ref DomainARN
        EndpointConfiguration: REGIONAL
        BasePath:
          - /
      EndpointConfiguration: REGIONAL
      AccessLogSetting:
        DestinationArn: !GetAtt DashboardApiLog.Arn
        Format: '{
          "requestId": "$context.requestId",
          "ip": "$context.identity.sourceIp",
          "requestTime": "$context.requestTime",
          "httpMethod": "$context.httpMethod",
          "routeKey": "$context.routeKey",
          "status": "$context.status",
          "protocol": "$context.protocol",
          "responseLength": "$context.responseLength",
          "integration error": "$context.integrationErrorMessage",
          }'

  # --- API LOGGING
  DashboardApiLog:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub ${AWS::StackName}-ApiLog
      RetentionInDays: 5

  # ––– EVENTBRIDGE TRIGGER
  DailyETLTrigger:
    Type: AWS::Events::Rule
    DependsOn:
      - DataIngestionFunction
    Properties:
      Name: !Sub ${AWS::StackName}-ETL-Trigger
      Description: Daily trigger for CGC ETL pipeline
      ScheduleExpression: rate(5 minutes)
      State: ENABLED
      Targets:
        - Arn: !GetAtt DataIngestionFunction.Arn
          Id: ETL_Lambda_function

  # ––– EVENTBRIDGE IAM ROLE
  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DataIngestionFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt DailyETLTrigger.Arn

  # ––– DATABASE
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-Data
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: date
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: date
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 2
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  # ––– DATABASE UPDATED SNS TOPIC
  DatabaseUpdatedTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: CRC-COVID-Database-Updated

  # ––– FUNCTION LAYER: PANDAS
  PandasLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.8
      Content:
        S3Bucket: quinceleaf-lambda-layers
        S3Key: lambda-layer-Python38-Pandas113.zip
      Description: Layer for Pandas 1.13 on Python 3.8
      LayerName: lambda-layer-Python38-Pandas113

  # ––– FUNCTION: STREAM
  ProcessDynamoDBStream:
    DependsOn:
      - DynamoDBTable
      - DatabaseUpdatedTopic
    Type: AWS::Serverless::Function
    Properties:
      Handler: cgc_covid_stream.lambda_handler
      CodeUri: functions/stream/
      Role: !GetAtt StreamFunctionExecutionRole.Arn
      FunctionName: !Sub ${AWS::StackName}-DatabaseStream
      Description: !Sub
        - Function for ${ResourceName}
        - ResourceName: Process stream of daily update
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt DynamoDBTable.StreamArn
            BatchSize: 1000
            Enabled: true
            MaximumBatchingWindowInSeconds: 60
            StartingPosition: TRIM_HORIZON
      Environment:
        Variables:
          TOPIC_ARN: !Ref DatabaseUpdatedTopic

  # ––– FUNCTION: ETL
  DataIngestionFunction:
    DependsOn:
      - DynamoDBTable
    Type: AWS::Serverless::Function
    Properties:
      Handler: cgc_covid_etl.lambda_handler
      Tracing: Active
      FunctionName: !Sub ${AWS::StackName}-ETL
      Description: !Sub
        - Function for ${ResourceName}
        - ResourceName: ETL of daily dataset
      CodeUri: functions/etl/
      Role: !GetAtt ETLFunctionExecutionRole.Arn
      Layers:
        - !Ref PandasLayer
      Environment:
        Variables:
          TABLE_NAME: !Ref DynamoDBTable
          TOPIC_ARN: !Ref DatabaseUpdatedTopic
          URL_DATASET_NYT: !Ref URLDatasetNYT
          URL_DATASET_JHU: !Ref URLDatasetJHU

  # ––– FUNCTION: API DATA
  DashboardApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: get_data.lambda_handler
      Runtime: python3.8
      MemorySize: 128
      Timeout: 15
      Tracing: Active
      FunctionName: !Sub ${AWS::StackName}-DashboardApiFunction
      Description: !Sub
        - Function for ${ResourceName}
        - ResourceName: CGC-COVID Dashboard API
      CodeUri: functions/api/get_data.py
      Role: !GetAtt ETLFunctionExecutionRole.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref DynamoDBTable
      Events:
        GetData:
          Type: Api
          Properties:
            Method: GET
            Path: /data
            RestApiId: !Ref DashboardApi

  # ––– FUNCTION: API CHECKPOINT
  CheckpointApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: get_checkpoint.lambda_handler
      Runtime: python3.8
      MemorySize: 128
      Timeout: 15
      Tracing: Active
      FunctionName: !Sub ${AWS::StackName}-CheckpointApiFunction
      Description: !Sub
        - Function for ${ResourceName}
        - ResourceName: CGC-COVID Checkpoint API
      CodeUri: functions/api/get_checkpoint.py
      Role: !GetAtt ETLFunctionExecutionRole.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref DynamoDBTable
      Events:
        GetData:
          Type: Api
          Properties:
            Method: GET
            Path: /checkpoint
            RestApiId: !Ref DashboardApi
